### ISSUE TITLE
Motion controls not working in Heavy Rain

### ISSUE THREAD

**Issue by nefh** [the-maazu/deckshock4#1]
Hi!
First of all, thank you for creating this tool. I am using it to get controller support in Heavy Rain from GOG.com on Steamdeck. This version of HR have very limited controller support - it only recognizes DS4. No X360, no steaminput etc.

I get deckshock4 to work after disabling steaminput in localconfig.vdf for HR and applying specified  proton version.

The game recognizes emulated DualShock4 and it works fine until sequences with motion controls. There is nothing, no any movement is recognized by the game.

Since shaking steamdeck is not comfortable anyway, maybe it would be possible to assign specific motion values to unused buttons on back of SteamDeck? E.g. top ones for left-right and bottom for up-down?

**Comment by the-maazu** [comment]
> The game recognizes emulated DualShock4 and it works fine until sequences with motion controls. There is nothing, no any movement is recognized by the game.

Can you check gyro mapping. Gyro must be enabled in inbuilt controller settings for this to work, I recommend setting it to joystick so it does not duplicate inputs. Without gyro bounded to something the hardware sends no data for the gyro to be translated.

> Since shaking steamdeck is not comfortable anyway, maybe it would be possible to assign specific motion values to unused buttons on back of SteamDeck? E.g. top ones for left-right and bottom for up-down?

This is a good idea, I will add this to the list of improvements to make.
