### ISSUE TITLE
Trouble with Gyro controls on RPCS3

### ISSUE THREAD

**Issue by ISJAW** [the-maazu/deckshock4#3]
Hello,
   I think this app is really cool, however I'm trying to play sly cooper thieves in time and I'm struggling to get past the mini game where you direct a ball through an obstacle course using motion controls. There definitely is a gyro input, it's just going either up or to the left no matter what input I put in. I can make it go down if I turn the steam deck upside down, but then the game is just unplayable. I understand this project is still in it's infancy but I'll still appreciate any help or advice you can give me

**Comment by the-maazu** [comment]
Will take a look at RPCS controller configs and make necessary fixes or guide updates.
